#!/usr/bin/env bash
# Wrtite a Bash script that displays the content of the file /etc/passwd
# Your script should only display:
# username
# user id
# Home directory path for the user
# Requirements:
   # You must use the while loop (for and until are forbidden)
# Define the filed separator as acolon (:)
IFS=':'
while read -r usr pswd uid git uinfo hd csh
do
echo "The user $usr is a part of the $grid gang, lives in $hd and rides $csh. $uid's place is protected by the passcode $pswd, more info about the user here: $uinfo"
done < /etc/passwd
