#!/usr/bin/env bash
# this script prints all process that are running
echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"; ps axo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest | tail -n +2
